Skip belastingdienst.nl nightly "crying wolf"
Almost every day it's the same, we get the error, we check the link,
it's fine. Just skip this one.

- ./_site/phases/09-contracting.html
  *  External link
https://www.belastingdienst.nl/wps/wcm/connect/bldcontenten/belastingdienst/business/business-public-benefit-organisations/public_benefit_organisations/what_is_pbo/what_is_a_pbo
failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or
perhaps the request timed out.
             Sometimes, making too many requests at once also breaks
things.
             Either way, the return message (if any) from the server is:
Failure when receiving data from the peer

HTML-Proofer found 1 failure!
Error: Process completed with exit code 1.